# Generated by Django 5.1.6 on 2025-02-13 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('start', models.TimeField(blank=True)),
                ('stop', models.TimeField(blank=True)),
                ('discription', models.CharField(blank=True, max_length=255)),
                ('create_ed', models.DateTimeField(auto_now_add=True)),
                ('update_ed', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'KURS',
                'verbose_name_plural': 'Kurslar',
                'ordering': ['-create_ed'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=40)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.CharField(blank=True, max_length=50)),
                ('kurs', models.IntegerField()),
                ('create_ed', models.DateTimeField(auto_now_add=True)),
                ('update_ed', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Talaba',
                'verbose_name_plural': 'Talabalar',
                'ordering': ['-create_ed'],
            },
        ),
    ]
