# Generated by Django 5.1.6 on 2025-02-13 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Univer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='kurs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Univer.kurs'),
        ),
    ]
