# Generated by Django 5.1.6 on 2025-02-13 15:07

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('Univer', '0002_alter_student_kurs'),
    ]

    operations = [
    ]
