# Generated by Django 5.1.6 on 2025-02-13 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Univer', '0003_auto_20250213_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='kurs',
            name='totalStudent',
            field=models.IntegerField(default=0),
        ),
    ]
