# Generated by Django 5.1.6 on 2025-02-21 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Univer', '0008_kompaniya_remove_news_category_avtomabil_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avtomabil',
            name='color',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='avtomabil',
            name='kuchi',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='avtomabil',
            name='price',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='avtomabil',
            name='year',
            field=models.TextField(max_length=50),
        ),
    ]
