# Generated by Django 5.1.6 on 2025-02-22 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Univer', '0009_alter_avtomabil_color_alter_avtomabil_kuchi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avtomabil',
            name='color',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='avtomabil',
            name='kuchi',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='avtomabil',
            name='price',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='avtomabil',
            name='title',
            field=models.CharField(max_length=50, verbose_name='model'),
        ),
        migrations.AlterField(
            model_name='avtomabil',
            name='year',
            field=models.CharField(max_length=50),
        ),
    ]
