# Generated by Django 5.1.6 on 2025-02-23 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Univer', '0010_alter_avtomabil_color_alter_avtomabil_kuchi_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kompaniya',
            options={'ordering': ['-created_ed'], 'verbose_name': 'KOMPANIYA', 'verbose_name_plural': 'KOMPANIYALAR'},
        ),
    ]
