# Generated by Django 5.1.6 on 2025-02-23 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Univer', '0011_alter_kompaniya_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avtomabil',
            old_name='kompaniyasi',
            new_name='kompaniya',
        ),
    ]
